name: java CI
on:
  push:
    branches: [ "main"]
  pull_request:
    branches:  [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v3

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Listar estructura del proyecto
      run: |
        echo "Contenido del directorio:"
        ls -la
        echo "Archivos java encontrados:"
        find . -name "*.java"
        
    - name: compilar con javac
      run: javac Main.java
      # 0 si esta en src: javac src/Main.java
      
    - name: Ejecutar programa
      run: java Main
      # 0 si esta en src: java -cp src Main
